services:
  backend:
    image: todo-back-prod
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - NODE_ENV=production
      - PORT=3000
    depends_on: # ensure that the dbs are loaded before attempting to use them, could also healthcheck these
      - mongo
      - redis
  mongo:
    image: mongo
    #ports:
    #  - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js #init script if no db exists
      - ./todo-backend/mongo_data:/data/db 
  redis:
    image: redis
    command: [ 'redis-server', '--appendonly', 'yes' ]
    #ports:
    #  - 6379:6379
    volumes:
      - ./todo-backend/redis_data:/data
  frontend:
    image: todo-front-prod
  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend